_wandb:
    value:
        cli_version: 0.26.1
        e:
            znmhmimmdmcl2b1tv30vvrq79h7xig26:
                args:
                    - --d_model
                    - "64"
                    - --n_layers
                    - "3"
                    - --ffn_dim
                    - "128"
                    - --qv-eps
                    - "2e-6"
                    - --kd-weight
                    - "0.3"
                    - --kd-temp
                    - "2.0"
                    - /home/users/kayamaguchi/BNJetTag/trainingDataSig.h5
                    - /home/users/kayamaguchi/BNJetTag/trainingDataQCD.h5
                    - /home/users/kayamaguchi/BNJetTag/sampleDataSig.h5
                    - /home/users/kayamaguchi/BNJetTag/sampleDataQCD.h5
                codePath: qkerasModel.py
                codePathLocal: qkerasModel.py
                cpu_count: 32
                cpu_count_logical: 64
                disk:
                    /:
                        total: "199900393472"
                        used: "156323651584"
                email: kayamaguchi@ucsd.edu
                executable: /home/users/kayamaguchi/micromamba/envs/bnjet/bin/python3
                git:
                    commit: 4c02c5fb10eb6bd1dc945715a704f55be3ff3681
                    remote: https://github.com/kai124138/BNJetTagKai.git
                host: mulder.t2.ucsd.edu
                memory:
                    total: "134749081600"
                os: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
                program: /home/users/kayamaguchi/BNJetTagKai/qkerasModel.py
                python: CPython 3.10.10
                root: /home/users/kayamaguchi/BNJetTagKai
                startedAt: "2026-05-20T09:13:47.675900Z"
                writerId: znmhmimmdmcl2b1tv30vvrq79h7xig26
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 3
                - 8
                - 13
                - 16
                - 62
            "4": 3.10.10
            "5": 0.26.1
            "10":
                - 17
            "12": 0.26.1
            "13": linux-x86_64
auc_loss:
    value: pauc1way
baseline:
    value: false
d_model:
    value: 64
deepsets:
    value: false
ffn_dim:
    value: 128
fp_edges:
    value: true
fpr_thresh:
    value: 0.01
kd_weight:
    value: 0.3
n_layers:
    value: 3
